
#include <bits/stdc++.h>
#include <omp.h>
using namespace std;
struct Sig{vector<int>v;bool operator<(Sig const&o)const{return v<o.v;}bool operator==(Sig const&o)const{return v==o.v;}};
static const int N=7,MM=127;
vector<int>dec(uint64_t z,int m){vector<int>e(m);for(int i=m-1;i>=0;--i){e[i]=z&127;z>>=7;}return e;}
vector<int>colors(vector<int>const&e){vector<vector<int>>inc(N);int cd[N][N]{};for(int a:e){int s=__builtin_popcount((unsigned)a);for(int i=0;i<N;i++)if(a>>i&1)inc[i].push_back(s);for(int i=0;i<N;i++)if(a>>i&1)for(int j=i+1;j<N;j++)if(a>>j&1)cd[i][j]++,cd[j][i]++;}vector<Sig>g(N);for(int i=0;i<N;i++){sort(inc[i].begin(),inc[i].end());g[i].v.push_back(inc[i].size());g[i].v.insert(g[i].v.end(),inc[i].begin(),inc[i].end());vector<int>x;for(int j=0;j<N;j++)if(i!=j)x.push_back(cd[i][j]);sort(x.begin(),x.end());g[i].v.push_back(-1);g[i].v.insert(g[i].v.end(),x.begin(),x.end());}vector<int>col(N);for(int rr=0;rr<N;rr++){map<Sig,int>mp;for(auto&s:g)mp[s]=0;int q=0;for(auto&z:mp)z.second=q++;for(int i=0;i<N;i++)col[i]=mp[g[i]];vector<Sig>h(N);for(int i=0;i<N;i++){h[i].v={col[i]};vector<vector<int>>ev;for(int a:e)if(a>>i&1){vector<int>x{__builtin_popcount((unsigned)a)};for(int j=0;j<N;j++)if(a>>j&1)x.push_back(col[j]);sort(x.begin()+1,x.end());ev.push_back(x);}sort(ev.begin(),ev.end());for(auto&x:ev){h[i].v.push_back(-2);h[i].v.insert(h[i].v.end(),x.begin(),x.end());}vector<pair<int,int>>p;for(int j=0;j<N;j++)if(i!=j)p.push_back({col[j],cd[i][j]});sort(p.begin(),p.end());h[i].v.push_back(-3);for(auto z:p){h[i].v.push_back(z.first);h[i].v.push_back(z.second);}}if(h==g)break;g.swap(h);}map<Sig,int>mp;for(auto&s:g)mp[s]=0;int q=0;for(auto&z:mp)z.second=q++;for(int i=0;i<N;i++)col[i]=mp[g[i]];return col;}
uint64_t canon(vector<int>const&e){auto col=colors(e);int nc=*max_element(col.begin(),col.end())+1;vector<vector<int>>G(nc);for(int i=0;i<N;i++)G[col[i]].push_back(i);vector<int>st(nc);int c=0;for(int g=0;g<nc;g++){st[g]=c;c+=G[g].size();}vector<int>mpv(N);uint64_t best=UINT64_MAX;function<void(int)>rec=[&](int g){if(g==nc){vector<int>a(e.size());for(int q=0;q<(int)e.size();q++){int y=0;for(int i=0;i<N;i++)if(e[q]>>i&1)y|=1<<mpv[i];a[q]=y;}sort(a.begin(),a.end());uint64_t z=0;for(int y:a)z=(z<<7)|y;best=min(best,z);return;}auto old=G[g];vector<int>lab(old.size());iota(lab.begin(),lab.end(),st[g]);do{for(int j=0;j<(int)old.size();j++)mpv[old[j]]=lab[j];rec(g+1);}while(next_permutation(lab.begin(),lab.end()));};rec(0);return best;}
long long det(array<array<long long,7>,7>a){long long prev=1,sg=1;for(int k=0;k<6;k++){int p=k;while(p<7&&!a[p][k])p++;if(p==7)return 0;if(p!=k){swap(a[p],a[k]);sg=-sg;}long long piv=a[k][k];for(int i=k+1;i<7;i++)for(int j=k+1;j<7;j++){__int128 z=(__int128)a[i][j]*piv-(__int128)a[i][k]*a[k][j];if(k)z/=prev;a[i][j]=(long long)z;}prev=piv;for(int i=k+1;i<7;i++)a[i][k]=0;}return sg*a[6][6];}
bool pos(vector<int>const&e){array<array<long long,7>,7>A{};for(int c=0;c<7;c++)for(int i=0;i<7;i++)A[c][i]=(e[c]>>i)&1;long long d=det(A);if(!d)return 0;for(int i=0;i<7;i++){auto B=A;for(int r=0;r<7;r++)B[r][i]=1;long long z=det(B);if((d>0&&z<=0)||(d<0&&z>=0))return 0;}return 1;}
int main(int ac,char**av){if(ac!=2)return 2;vector<unordered_set<uint64_t>>L(7);for(int a=1;a<MM;a++)L[1].insert(canon({a}));for(int r=1;r<6;r++){for(auto z:L[r]){auto e=dec(z,r);for(int a=1;a<MM;a++){bool ok=1;for(int b:e)if((a&b)==a||(a&b)==b){ok=0;break;}if(ok){auto f=e;f.push_back(a);L[r+1].insert(canon(f));}}}cerr<<"level "<<r+1<<" "<<L[r+1].size()<<"\n";}vector<uint64_t>P(L[6].begin(),L[6].end());vector<unordered_set<uint64_t>>loc(max(1,omp_get_max_threads()));
#pragma omp parallel for schedule(dynamic,16)
for(size_t z=0;z<P.size();z++){int tid=omp_get_thread_num();auto e=dec(P[z],6);for(int a=1;a<MM;a++){bool ok=1;for(int b:e)if((a&b)==a||(a&b)==b){ok=0;break;}if(!ok)continue;auto f=e;f.push_back(a);sort(f.begin(),f.end());if(pos(f))loc[tid].insert(canon(f));}}
unordered_set<uint64_t>A;for(auto&x:loc)for(auto z:x)A.insert(z);vector<uint64_t>v(A.begin(),A.end());sort(v.begin(),v.end());ofstream fo(av[1]);for(auto z:v){auto e=dec(z,7);fo<<7;for(int a:e)fo<<" "<<a;fo<<"\n";}cerr<<"positive7 "<<v.size()<<"\n";}
