
#include <bits/stdc++.h>
#include <boost/multiprecision/cpp_int.hpp>
#include <boost/rational.hpp>
using namespace std;using I=boost::multiprecision::cpp_int;using R=boost::rational<I>;
string rs(R a){return a.numerator().convert_to<string>()+(a.denominator()==1?"":"/"+a.denominator().convert_to<string>());}
struct LP{int m,n;vector<int>B,N;vector<vector<R>>D;LP(vector<vector<R>>const&A,vector<R>const&b,vector<R>const&c):m(b.size()),n(c.size()),B(m),N(n+1),D(m+2,vector<R>(n+2)){for(int i=0;i<m;i++)for(int j=0;j<n;j++)D[i][j]=A[i][j];for(int i=0;i<m;i++)B[i]=n+i,D[i][n]=-1,D[i][n+1]=b[i];for(int j=0;j<n;j++)N[j]=j,D[m][j]=-c[j];N[n]=-1;D[m+1][n]=1;}void piv(int r,int s){R inv=R(1)/D[r][s];for(int i=0;i<m+2;i++)if(i!=r)for(int j=0;j<n+2;j++)if(j!=s)D[i][j]-=D[r][j]*D[i][s]*inv;for(int j=0;j<n+2;j++)if(j!=s)D[r][j]*=inv;for(int i=0;i<m+2;i++)if(i!=r)D[i][s]*=-inv;D[r][s]=inv;swap(B[r],N[s]);}bool simp(int ph){int x=ph==1?m+1:m;while(1){int s=-1;for(int j=0;j<=n;j++){if(ph==2&&N[j]==-1)continue;if(s<0||D[x][j]<D[x][s]||(D[x][j]==D[x][s]&&N[j]<N[s]))s=j;}if(D[x][s]>=0)return 1;int r=-1;for(int i=0;i<m;i++)if(D[i][s]>0){if(r<0)r=i;else{R a=D[i][n+1]/D[i][s],b=D[r][n+1]/D[r][s];if(a<b||(a==b&&B[i]<B[r]))r=i;}}if(r<0)return 0;piv(r,s);}}pair<int,R>solve(){int r=0;for(int i=1;i<m;i++)if(D[i][n+1]<D[r][n+1])r=i;if(D[r][n+1]<0){piv(r,n);if(!simp(1)||D[m+1][n+1]<0)return{-1,0};if(D[m+1][n+1]!=0)return{-1,0};auto it=find(B.begin(),B.end(),-1);if(it!=B.end()){r=it-B.begin();int s=0;for(int j=1;j<=n;j++)if(D[r][j]<D[r][s]||(D[r][j]==D[r][s]&&N[j]<N[s]))s=j;piv(r,s);}}if(!simp(2))return{1,0};return{0,D[m][n+1]};}};
vector<R> solve_square(vector<vector<int>>A){int n=A.size();vector<vector<R>>M(n,vector<R>(n+1));for(int r=0;r<n;r++){for(int c=0;c<n;c++)M[r][c]=A[c][r];M[r][n]=1;}for(int c=0;c<n;c++){int p=c;while(p<n&&M[p][c]==0)p++;if(p==n)throw runtime_error("singular");swap(M[p],M[c]);R inv=R(1)/M[c][c];for(int j=c;j<=n;j++)M[c][j]*=inv;for(int i=0;i<n;i++)if(i!=c&&M[i][c]!=0){R f=M[i][c];for(int j=c;j<=n;j++)M[i][j]-=f*M[c][j];}}vector<R>a(n);for(int i=0;i<n;i++)a[i]=M[i][n];return a;}
struct C{int k;vector<int>mask;array<int,7>h;vector<vector<int>>A;vector<R>alpha;long long nodes=0;
 R check(vector<pair<int,int>>const&fail){int m=7,nv=8,E=7;vector<vector<R>>Q;vector<R>b;auto add=[&](vector<R>r,R z){Q.push_back(move(r));b.push_back(z);};
  for(int c=0;c<m;c++){vector<R>r(nv);r[c]=-1;r[E]=1;add(r,0);r.assign(nv,0);r[c]=1;r[E]=1;add(r,1);}
  for(int i=0;i<7;i++){vector<R>r(nv);for(int c=0;c<m;c++)r[c]=-A[i][c];r[E]=1;add(r,-h[i]);r.assign(nv,0);for(int c=0;c<m;c++)r[c]=A[i][c];r[E]=1;add(r,h[i]+1);}
  for(auto [i,j]:fail){vector<R>r(nv);if(j<0){for(int c=0;c<m;c++)r[c]=-alpha[i]*A[i][c];R rhs=-alpha[i]*h[i]-R(k,7)*(1-alpha[i]);add(r,rhs);}else{for(int c=0;c<m;c++)r[c]=-alpha[i]*A[i][c]-alpha[j]*A[j][c];R rhs=-alpha[i]*h[i]-alpha[j]*(1+h[j]);add(r,rhs);}}
  vector<R>r(nv);for(int c=0;c<m;c++)r[c]=1;add(r,k);for(int c=0;c<m;c++)r[c]=-1;add(r,-k);vector<R>obj(nv);obj[E]=1;nodes++;auto z=LP(Q,b,obj).solve();return z.first==0?z.second:R(-1);
 }
 bool dfs(int i,vector<pair<int,int>>&f){R e=check(f);if(e<=0)return 0;if(i==7)return 1;f.push_back({i,-1});if(dfs(i+1,f))return 1;f.pop_back();for(int j=0;j<7;j++)if(j!=i){f.push_back({i,j});if(dfs(i+1,f))return 1;f.pop_back();}return 0;}
};
int main(int ac,char**av){if(ac!=2)return 2;ifstream f(av[1]);string l;long long cells=0,nodes=0;while(getline(f,l)){stringstream z(l);char P;int m,k;z>>P>>m>>k;if(m!=7)continue;C c;c.k=k;c.mask.resize(7);for(int&i:c.mask)z>>i;string hs;z>>hs;if(hs[0]=='|')hs=hs.substr(1);else{string q;z>>q;hs=q.substr(1);}for(int i=0;i<7;i++)c.h[i]=hs[i]-'0';c.A.assign(7,vector<int>(7));for(int i=0;i<7;i++)for(int j=0;j<7;j++)c.A[i][j]=(c.mask[j]>>i)&1;c.alpha=solve_square(c.A);for(auto a:c.alpha)if(a<=0)throw runtime_error("nonpositive alpha");vector<pair<int,int>>ff;if(c.dfs(0,ff)){cerr<<"BAD square cell: "<<l<<"\n";return 1;}cells++;nodes+=c.nodes;}cerr<<"square_cells "<<cells<<" exact_lp_nodes "<<nodes<<"\n";}
